--- 
- hosts: all
  tasks:
  - debug:
      msg: "Installing docker engine"
  - import_role:
      name: dockerengine
  - debug:
      msg: "Initializing docker swarm"
  - import_role:
      name: swarminit

